default:
    just --list

cloc:
    cloc . --by-file --force-lang=Rust,lalrpop --list-file=.cloc

test *ARGS:
    ./tools/testsuite.py {{ARGS}}

run-test *ARGS:
    ./tools/testsuite.py --run {{ARGS}}

run WASM *ARGS:
    ./runtime/run.mjs {{WASM}} {{ARGS}}

compile SOURCE OUTPUT="module.wasm" LOG_LEVEL="error" *ARGS="": build
    RUST_LOG={{LOG_LEVEL}} ./target/debug/c_to_wasm_compiler {{SOURCE}} -o {{OUTPUT}} {{ARGS}}

build:
    cargo build

objdump WASM:
    wasm-objdump {{WASM}} -d

profile-stack LOGFILE *ARGS:
    ./tools/profiler.py stack {{LOGFILE}} {{ARGS}}

clear-logs:
    rm ./logs/*.stackptrlog
