mod allocate_local_vars;
mod backend_error;
mod float_encoding;
mod import_export_names;
mod initialise_memory;
mod integer_encoding;
mod memory_constants;
mod memory_operations;
mod stack_frame_operations;
pub mod target_code_generation;
mod target_code_generation_context;
mod to_bytes;
mod vector_encoding;
mod wasm_indices;
mod wasm_instructions;
mod wasm_module;
mod wasm_types;
