mod aggregate_type_initialisers;
pub mod ast_to_ir;
mod compile_time_eval;
mod context;
mod get_ast_type_info;
pub mod ids;
pub mod instructions;
pub mod ir;
pub mod ir_types;
mod middle_end_error;
pub mod middle_end_optimiser;
mod type_conversions;
